export const DEPARTMENTS = [
  "Mayor's Office",
  "Vice Mayor's Office",
  "Sangguniang Bayan Office",
  "General Services Office (GSO)",
  "Accounting Office",
  "Budget Office",
  "Treasury Office (MTO)",
  "Assessor's Office",
  "Civil Registry (MCR)",
  "HR Office",
  "Engineering Office",
  "Agriculture",
  "MENRO",
  "LYDO",
  "Tourism",
  "DSWD",
  "DSWD - PDAO",
  "DSWD - Senior Citizen",
  "Rural Health Unit (RHU)",
  "MPDO",
  "BPLO",
  "PESO",
  "DILG",
  "Comelec",
]
